### PR TITLE
duration_format support with Python3 and background exclusion

### PR DESCRIPTION
**Pull request by avanzzzi**
When feature file is written in another language, the keyword 'Background' will change. Searching and removing by type will work for any language;
Builtin long() does not exist anymore, changing to int() adds python 3 support when using duration_format=True;

### CODE REVIEW

**Comment by dunossauro** [comment]
@avanzzzi nice <3

**Comment by avanzzzi** [comment]
63d6097 Fixes #6

**Comment by andreybehalf** [comment]
Did you verify your changes are backward compatible with python 2.7?
Thanks.

**Comment by avanzzzi** [comment]
> Did you verify your changes are backward compatible with python 2.7?

Yes, works as expected.
The int() function produces the same result as the long() function except that in python 2.7, when dealing with long numbers, the int() function will suffix the number with the letter L. The json parser in python 2.7 knows how to handle this and will write the number without the L in the output json.

**Pull request merged**
